name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      
      - run: cd plugin
      - run: npm ci
      - run: npm run compile

      - run: cd ../examples
      - run: npm ci
      - run: npm run e2
