name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin

    strategy:
      matrix:
        node-version: [10.x]

    steps:      
      - run: cd plugin
      - run: npm i
      - run: npm run compile

  verify_examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples

    strategy:
      matrix:
        node-version: [10.x]

    steps: 
      - run: cd ../examples
      - run: npm ci
      - run: npm run e2
